### ISSUE TITLE
Version 9.0

### ISSUE THREAD

**Issue by DenisSokoloff** [myflashlab/common-dependencies-ANE#2]
Do you plan to move to 9.0 version?

**Comment by myflashlab** [comment]
Could you please specify what are the features that you may have found interesting that V9.0 has but not the current version?

**Comment by myflashlab** [comment]
We have updated the dependencies to V9.0.1 because we are now developing the Firebase ANE which works only with GooglePlayServices 9.0.0 or higher. 

While updating your ANEs to the latest version, make sure to read the change log for each ANE because now that we are on V9.0.1, some ANEs may require more dependency than before.

**Comment by DenisSokoloff** [comment]
- does facebook ANE work with new version common-dependencies-ANE?
- when admob+firebase ane be done?

**Comment by myflashlab** [comment]
Facebook does not use any of the GooglePlayServices dependency ANEs!
The Admob ANE will be released on Monday, tomorrow. (we hope :)
The Firebase ANE still needs more touches to be ready. soon, we hope. We're working on it.

**Comment by DenisSokoloff** [comment]
yes I know but I used androidSupport.ane and overrideAir.ane from this git.
oops I see its 8.4.0 still is ok

great - waiting Monday
