### ISSUE TITLE
Compatibility with AmazonIAP

### ISSUE THREAD

**Issue by Dimonte** [myflashlab/common-dependencies-ANE#28]
Hi!

Recently we decided to switch all our project's ANEs to MyFlashLab ones, but we have a problem with our Amazon build. AmazonIapV2Extension raises the following conflict with overrideAir.ane:

     [exec] dx tool failed:
     [exec] UNEXPECTED TOP-LEVEL EXCEPTION:
     [exec] java.lang.IllegalArgumentException: already added: Lcom/google/gson/annotations/Expose;

Is it possible to make a variant of this extension that is compatible with Amazon's IAP one? Or could you provide us with the source code for the overrideAir.ane so we can fix it ourselves?

**Comment by myflashlab** [comment]
Yeah, it’s already fixed but not yet released. In normal circumstances, we could have release the fixed version but this time, you have to wait for a few more days before we release the new version. You may ask why. Because we are doing some heavy fundamental ANE releases and ANELAB software release based on the new Overrideair which will make conflicts if released separately. So we have to release them all together. We are hoping to do this on the weekend.

**Comment by myflashlab** [comment]
V5.6.1 of OverrideAir has been released a few days ago, Also make sure you are updating all your other ANEs to avoid compilation errors.

You may like to join our mailing list to be notified with the latest releases: https://t.co/TMpfNQlEUR

**Comment by Dimonte** [comment]
Works now, thank you.
